### ISSUE TITLE
Certain Data not reflected in Edit Profile

### ISSUE THREAD

**Issue by Bony5690** [SolveSmartCities/SolveSmartCities.App#140]
The Family Section and the skills the client is training for from the training section is not reflected when you click into the view profile page. I think reflecting what skills they are looking to get trained for or currently training for would be good  to show on the view profile section. Also when clicking into the edit profile page the training section does not show what skills they are training for.

username: admin@scc.com
password: Testing!123

1. Log in to super user admin
2. click view for drop down menu for Start to Finish
3. Click View Profile.
4. Repeat steps 1 to 2 but click edit profile to see what data is reflected in the training section.

**Comment by reidcompton** [comment]
@Bony5690 -- I'm going to break this into two issues. The "skills not showing on edit profile page" issue is legitimate, it looks like that section on the edit page is out of sync with the data we collect on that page now.

The View Profile page not have some data points is by design, but we should revisit it and see what other data we can incorporate into that page to be the most helpful, so I'll open another ticket for that.

**Comment by Bony5690** [comment]
ok that sounds good
