### ISSUE TITLE
Email Sent Out For Member to Create Profile

### ISSUE THREAD

**Issue by mattweevu** [SolveSmartCities/SolveSmartCities.App#99]
Used mstrauss+life@solvesmartcities.com / mstrauss+peterpan@solvesmartcities.com 

and both had bugs when creating profiles... different bugs. 

Attached are screenshots. 
![screen shot 2017-06-09 at 7 58 06 pm](https://user-images.githubusercontent.com/11169109/26998747-342c0502-4d4e-11e7-824c-93030cd70ece.png)
![screen shot 2017-06-09 at 7 54 28 pm](https://user-images.githubusercontent.com/11169109/26998750-3431094e-4d4e-11e7-8a84-b5de2413e77e.png)
![screen shot 2017-06-09 at 7 54 10 pm](https://user-images.githubusercontent.com/11169109/26998748-342f923a-4d4e-11e7-8019-1ed15bfad400.png)
![screen shot 2017-06-09 at 7 53 00 pm](https://user-images.githubusercontent.com/11169109/26998749-3430ec0c-4d4e-11e7-9400-9468bc718562.png)

**Comment by reidcompton** [comment]
@mattweevu -- What were the bugs?

**Comment by mattweevu** [comment]
So when I was on staging - john@workforcework.org. Here's what happened:
1) Add client - typed in first name , last name and submit and email
2) Got the email and pressed the button and it wouldn't let me log in, or it logged me in as john at workforce works? 


![screen shot 2017-06-09 at 8 56 05 pm](https://user-images.githubusercontent.com/11169109/26999043-35270fc6-4d56-11e7-8142-83f08efd5b56.png)
![screen shot 2017-06-09 at 8 56 05 pm](https://user-images.githubusercontent.com/11169109/26999050-62055c46-4d56-11e7-81da-446a5234c137.png)

**Comment by reidcompton** [comment]
This sounds like more of a testing scenario, trying to switch users rapidly. I'm assuming you didn't log out of the john@ account before registering, so when you registered as peterpan, it created the user, but then checked your cookie and saw that you were still john@, so routed you back to his page. Then when you tried to register again, Peterson was already taken, because your registration actually did succeed the first time.

This scenario is less likely in the real world, but it's a relatively easy task to just logout the user when they first hit the register page, so I will incorporate that change, which should prevent this from happening again.

**Comment by mattweevu** [comment]
I thought of that and logged out and logged in. It probably was still a bit confused with the cookies and history, as you said. 

Can you send me two or three links to register - one with a soft skills nonprofit, 2nd with both a soft skills and workforce nonprofit, 3rd with just a workforce nonprofit, then lastly (4th) with a prop manager? 

This will just get me thinking about where the profiles have to go and where not to.  

- Matt

**Comment by reidcompton** [comment]
You're right, this is a bug. I found the source and pushed out a fix.
